.PHONY: all
all: MIMARKS_Data_combined.csv metabolites.csv microbe.rda ps.rds rdp_train_set_14.fa.gz

MIMARKS_Data_combined.csv:
	wget "https://raw.githubusercontent.com/spholmes/F1000_workflow/master/data/MIMARKS_Data_combined.csv"
	
metabolites.csv:
	wget "https://raw.githubusercontent.com/spholmes/F1000_workflow/master/data/metabolites.csv"
	
microbe.rda:
	wget "https://raw.githubusercontent.com/spholmes/F1000_workflow/master/data/microbe.rda"
	 
ps.rds: 
	wget "https://raw.githubusercontent.com/spholmes/F1000_workflow/master/data/ps.rds"
	
rdp_train_set_14.fa.gz:
	wget "https://raw.githubusercontent.com/spholmes/F1000_workflow/master/data/rdp_train_set_14.fa.gz"	